object-templates-raw: |
  {{hub- $devicePaths := (index .ManagedClusterLabels "autoshift.io/lvm-device-paths" | default "") hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: lvm.topolvm.io/v1alpha1
      kind: LVMCluster
      metadata:
        name: lvmcluster
        namespace: openshift-storage
      spec:
        storage:
          deviceClasses:
            - default: '{{hub index .ManagedClusterLabels "autoshift.io/lvm-default" | default "true" | toBool hub}}'
              fstype: '{{hub index .ManagedClusterLabels "autoshift.io/lvm-fstype" | default "xfs" hub}}'
              name: vg1
  {{hub- if not (empty $devicePaths) hub}}
              deviceSelector:
                paths:
  {{hub- range $path := (splitList "," $devicePaths) hub}}
                  - {{hub $path | trim hub}}
  {{hub- end hub}}
  {{hub- end hub}}
              thinPoolConfig:
                chunkSizeCalculationPolicy: Static
                metadataSizeCalculationPolicy: Host
                sizePercent: '{{hub index .ManagedClusterLabels "autoshift.io/lvm-size-percent" | default 90 | toInt hub}}'
                name: thin-pool-1
                overprovisionRatio: '{{hub index .ManagedClusterLabels "autoshift.io/lvm-overprovision-ratio" | default 10 | toInt hub}}'
